---
- name: Test connectivity to servers
  hosts: localhost   # Replace with your inventory group or hostname
  gather_facts: false
  collections:
    - community.general

  tasks:
    - name: GET request
      ansible.builtin.uri:
        url: https://fakerestapi.azurewebsites.net/api/v1/Activities
    - name: GET request 2
      ansible.builtin.uri:
        url: https://fakerestapi.azurewebsites.net/api/v1/Activities/
        method: GET
        status_code: 200
        return_content: true
      register: API_output
    - name : Display the value to fail
      ansible.builtin.debug:
        var : API_output.content
    - name: Initialize `variable1`
      ansible.builtin.set_fact:
        variable1: []

    - name: Build `variable1` list from API output
      ansible.builtin.set_fact:
        variable1: "{{ (variable1 | default([])) + [{ 'id': activity.Id, 'title': activity.Title, 'dueDate': activity.DueDate, 'completed': activity.Completed }] }}"
      loop: "{{ API_output.json }}"
      loop_control:
        loop_var: activity
    






