---
- name: Test connectivity to servers
  hosts: localhost   # Replace with your inventory group or hostname
  gather_facts: false
  collections:
    - name: community.general
      version: ">=8.0.0"

  tasks:
    - name: GET request
      ansible.builtin.uri:
        url: https://fakerestapi.azurewebsites.net/api/v1/Activities
    - name: GET request 2
      ansible.builtin.uri:
        url: https://fakerestapi.azurewebsites.net/api/v1/Activities/2
        method: GET
        status_code: 200
        return_content: true
      register: API_output
    - name : Display the value to fail
      ansible.builtin.debug:
        var : API_output.content
    - name : Display the value
      ansible.builtin.debug:
        var : API_output.json.dueDate
    - name: Format due date
      ansible.builtin.debug:
        msg: "{{ API_output.json.dueDate | ansible.community.to_datetime | strftime('%a %d %b %Y %H:%M:%S GMT') }}"






