---
- name: Test connectivity to servers
  hosts: localhost   # Replace with your inventory group or hostname
  gather_facts: false
  tasks:
    - name: GET request
      ansible.builtin.uri:
        url: https://api.restful-api.dev/objects/7
