---
- name: Test connectivity to servers
  hosts: localhost   # Replace with your inventory group or hostname
  gather_facts: false
  collections:
    - community.general
    
  tasks: 
    - name: GET request single multiple or none
      ansible.builtin.uri:
        url: https://fakerestapi.azurewebsites.net/api/v1/Activities/2
        method: GET
        status_code: 200
        return_content: true
      register: API_output

    - name: Normalize response into a list
      ansible.builtin.set_fact:
        activities_list: >-
          {{
            (API_output.json | default([]))
            if (API_output.json | type_debug) == 'list'
            else (
              (API_output.json | type_debug) == 'dict'
              | ternary([API_output.json], [])
            )
          }}

    - name: Display each activity
      ansible.builtin.debug:
        msg: "ID={{ item.id | default(item.Id) }} Title={{ item.title | default(item.Title) }} Due={{ item.dueDate | default(item.DueDate) }} Completed={{ item.completed | default(item.Completed) }}"
      loop: "{{ activities_list }}"
      loop_control:
        loop_var: item

    - name: Render activities HTML
      ansible.builtin.template:
        src: templates/activities.html.j2
        dest: ./activities.html
        mode: '0644'
      vars:
        activities: "{{ activities_list }}"

    - name: Build HTML report
      ansible.builtin.set_fact:
        object_report_html: |
          <html>
            <head><title>Activities Report</title></head>
            <body>
              <table border="1" cellpadding="5" cellspacing="0">
                <tr>
                  <th>ID</th>
                  <th>Title</th>
                  <th>Due Date</th>
                  <th>Completed</th>
                </tr>
                {% for activity in activities_list %}
                <tr>
                  <td>{{ activity.id | default(activity.Id) }}</td>
                  <td>{{ activity.title | default(activity.Title) }}</td>
                  <td>{{ activity.dueDate | default(activity.DueDate) }}</td>
                  <td>{{ activity.completed | default(activity.Completed) }}</td>
                </tr>
                {% endfor %}
              </table>
            </body>
          </html>

    - name: Save HTML report into AWX job artifacts
      ansible.builtin.set_stats:
        data:
          object_report_html: "{{ object_report_html }}"
