---
- name: Test connectivity to servers
  hosts: localhost   # Replace with your inventory group or hostname
  gather_facts: false
  collections:
    - community.general

  tasks:
    - name: GET request
      ansible.builtin.uri:
        url: https://fakerestapi.azurewebsites.net/api/v1/Activities
    - name: GET request 2
      ansible.builtin.uri:
        url: https://fakerestapi.azurewebsites.net/api/v1/Activities/
        method: GET
        status_code: 200
        return_content: true
      register: API_output
    - name : Display the value to fail
      ansible.builtin.debug:
        var : API_output.content
    - name : Display the value
      ansible.builtin.set_fact: >-
        variable1: "{{ variable1+ [{ 
        'id': var1.Id, 
        'title':  var1.Title, 
        'dueDate': var1.DueDate, 
        'completed': var1.Completed
        }] }}"
      loop: "{{ API_output.json }}"
      loop_control:
        loop_var: var1
    






